# Generated by Django 5.2.1 on 2025-05-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_id', models.CharField(db_index=True, max_length=200, null=True, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_id', models.CharField(db_index=True, max_length=200, null=True, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_id', models.CharField(db_index=True, max_length=200, null=True, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('reseller', 'Reseller')], default='individual', max_length=200)),
                ('preferred_payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online Payment'), ('credit', 'Credit Card'), ('upi', 'UPI')], default='cash', max_length=200)),
                ('delivery_schedule', models.CharField(choices=[('morning', 'Morning (6AM - 9AM)'), ('evening', 'Evening (4PM - 7PM)'), ('both', 'Both Morning & Evening')], default='morning', max_length=200)),
                ('delivery_frequency', models.CharField(choices=[('daily', 'Daily'), ('alternate', 'Alternate Days'), ('weekly', 'Weekly')], default='daily', max_length=200)),
                ('additional_notes', models.TextField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='dairy.cities')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='dairy.states')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='MilkSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_id', models.CharField(db_index=True, max_length=200, null=True, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('quantity', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.customer')),
            ],
            options={
                'db_table': 'milk_sale',
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='dairy.states'),
        ),
    ]
