# Generated by Django 5.2.1 on 2025-05-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='mix_mil_rate',
            new_name='mix_milk_rate',
        ),
    ]
